### PR TITLE
Adds more pixel-perfect graphical codepoints.

### LINKED ISSUE #419: Pixel-perfect rendering for Block Elements & Symbols for Legacy Computing
### Motivation

Providing a pixel-perfect version of these should guarantee always best visual user experience.

### Specification

Good overview is actually here:

* Block Elements: https://www.unicode.org/charts/PDF/U2580.pdf
* Symbols for Legacy Computing: https://www.unicode.org/charts/PDF/U1FB00.pdf

But also:

* https://en.wikipedia.org/wiki/Box-drawing_character#Block_Elements
* https://en.wikipedia.org/wiki/Box-drawing_character#Symbols_for_Legacy_Computing

### LINKED ISSUE #437: Pixel perfect rendering of sextant blocks (1FB00..3B)
As mentioned in #424 by @dankamongmen.

### PR DESCRIPTION
**Pull request by christianparpart**
refs #424, #441
closes #437, #419

Update: I am not going to implement all possible box drawings and terminal-alike codepoints in one single PR.
Ticket #441 is used to keep track of the progress.

### CODE REVIEW

**Comment by christianparpart** [comment]
@dankamongmen, I did find http://www.unicode.org/charts/PDF/U1FB00.pdf and it seems there is even much more than that, and also, Kitty has implemented quite many of these (and more) to construct pixel-perfect graphics.

Now I wonder which of these you (notcurses) makes really use of, apart from the few you mentioned. Is there anything else I should implement to make notcurses look pretty?

**Comment by dankamongmen** [comment]
> @dankamongmen, I did find http://www.unicode.org/charts/PDF/U1FB00.pdf and it seems there is even much more than that, and also, Kitty has implemented quite many of these (and more) to construct pixel-perfect graphics.
> 
> Now I wonder which of these you (notcurses) makes really use of, apart from the few you mentioned. Is there anything else I should implement to make notcurses look pretty?

I use the following:
* pretty much all line- and box-drawing characters
* the halfblocks (for 2x1 blitter)
* the quadrants (for 2x2 blitter)
* the sextants (for 3x2 blitter)
* the eighths in all directions (for plots)

those are the most important ones aside, of course, from whatever the user is pumping through.

i do not yet use the angled block characters from the Symbols for Legacy Computing, but i intend to make use of them in plots down the road.

**Comment by christianparpart** [comment]
Ok nice. Let me make sure I have all of the above part of this PR.

Would you mind replying to my emoji-vs-width question i had in the starter ticket? :-)

**Comment by christianparpart** [comment]
> I use the following:
> 
>   * pretty much all line- and box-drawing characters
>   * the halfblocks (for 2x1 blitter)
>   * the quadrants (for 2x2 blitter)
>   * the sextants (for 3x2 blitter)
>   * the eighths in all directions (for plots)

@dankamongmen that's the implementation status inside this PR:

- [ ]  pretty much all line- and box-drawing characters
- [x]  the halfblocks (for 2x1 blitter)
- [x]  the quadrants (for 2x2 blitter)
- [x]  the sextants (for 3x2 blitter)
- [x]  the eighths in all directions (for plots)

And the Changelog reads like that (much more precise):

```
Adds more pixel-perfect graphical codepoints:
- U+23A1..U+23A6
- U+2580..U+2590
- U+2594..U+259F
- U+1FB00..U+1FB3B
- U+1FB70..U+1FB8B
```

With "all eights in all directions" I assume you mean horizontal and vertical, as I assume there is no diagonal, is there? Well, yeah, the horiz/vert-ones are now part of this PR, too.

With "pretty much all line- and box-drawing characters" I am not sure I do cover that. Does notcurses have all magic line/box drawing codepoints in one file so that I can check against? :-)

I also noticed that `notcurses-info` is a little treasure as it tells me what I apparently do not handle manually (without font file) yet. I think the purpose of that program for **you** was to see if a TE actually looks good with these or even cannot render some of these at all. Now Contour is still missing a few to be manually implemented (as far as  `notcurses-info` is concerned), but assuming that you also use ALL of these inside your lib, I'll be then adding them. But not all in that one PR, as it's already pretty big. I want to get current additions out ASAP, so whatever is missing and interesting will hopefully follow in follow-up PRs soon.

**Comment by dankamongmen** [comment]
everything I use is definitely represented in notcurses-info, whose purpose is exactly what you've ascertained -- I can look at it and know whether I ought expect some given terminal to look right or not.

if you handle everything there, you're handling everything I explicitly use.

by the eighths, I mean the "upper seven eighths", "left five eighths" etc. glyphs, and also the "horizontal bar five eighths down" etc. I'm at dinner right now but basically the lower  left corner and the two big "pyramids"

**Comment by christianparpart** [comment]
At dinner? And i assumed you were moving in my country and timezones (it is 2:22 AM). OK thanks. I will do my best to get it good looking.

P.s. why don't i see the graphics on the top right anymore?

**Pull request merged**
