### PR TITLE
fix to build with boxed-cpp

### PR DESCRIPTION
**Pull request by topazus**
## Description

The PR is related to https://github.com/contour-terminal/boxed-cpp/pull/9

## How Has This Been Tested?

- [ ] Please describe how you tested your changes.
- [ ] see how your change affects other areas of the code, etc.

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

- [ ] I have read the [**`CONTRIBUTING`**](https://github.com/contour-terminal/contour/blob/master/CONTRIBUTING.md) document in my spoken language, and understand the terms
- [ ] I have updated (or added) the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have gone through all the steps, and have thoroughly read the instructions

### CODE REVIEW

**Comment by Yaraslaut** [comment]
@topazus  Can you update github action then please? If you are bussy i can do it as well

**Comment by topazus** [comment]
I do not have a compuer at hand right now. Grateful if you do this. @Yaraslaut

**Comment by Yaraslaut** [comment]
@topazus  I updated PR, builds are fine now, if you fill that PR is no longer in draft, make it then ready for review to proceeed with merging

**Review by christianparpart — CHANGES_REQUESTED** [review]
I just have a minor improvement suggestion. Otherwise, many thanks!

**Review by christianparpart — APPROVED** [review]

**Pull request merged**
