### PR TITLE
VT extension: passive mouse reporting & text selection reporting

### PR DESCRIPTION
**Pull request by christianparpart**
The drafted spec WAS is here: https://gist.github.com/christianparpart/bf82bc3a8ad7f3abeee3ada41c3178a9
but NOW located here: https://github.com/contour-terminal/vt-extensions

This adds support for allowing the terminal application to request mouse events, passively, i.e. the user can still select text as he'd be able to do when no app has requested mouse event tracking.

This feature does make sense in situations where the shell (ZSH, fish, bash, ...) might want to implement:

- reposition the cursor to where the mouse has been clicked in the command prompt
- tooltips of the command the mouse cursor is currently hovering

The problem without implementing such a VT extension is, that shells would never try to implement such features, as the user experience (no mouse-based select support) would be drained. Having this extension should be a win-win situation.

@jerch, @lhecker, @dankamongmen do you see any major problem here?  Would you guys be interested in something like this on your end, too?

### CODE REVIEW

**Comment by dankamongmen** [comment]
neat! let me take a look at this over the weekend and get back to you with any thoughts i might have. looks like good stuff on first, cursory inspection.

**Comment by christianparpart** [comment]
@dankamongmen : @jerch mentioned concerns wrt scrollback buffer and changed viewports to see parts or all of it. The mouse reporting's line number should always of course not take viewport into account and pass a value as if nothing was scrolled off. Also, the app would not receive events for coordinates it cannot access (e.g. scrollback lines) anyways. I'll adapt my code accordingly to that tonight.

**Comment by christianparpart** [comment]
We extended the idea a bit and also add a second VT extension to the passive mouse reporting mode, which is: reporting text selection events.


[contour-passive-mouse-and-selection-report-extension.webm](https://user-images.githubusercontent.com/56763/205448865-22515c02-5c86-4aff-826d-16cd5945316f.webm)

**Comment by jerch** [comment]
@christianparpart With the text selection event I am not sure anymore, if thats going into the right direction. Reasons:

- Text selection may be the result of different user interactions (depending on what the TE implements here), its not strictly pointer/mouse bound anymore. Means you are leaving mouse realms.
- Text selection, while def. useful on alternate buffer where the app can assume to control the screen state, is almost useless on scrollbuffer - due to the mixed output sources from other processes. Here it would be more interesting, if the selected text could be sent along, but anything in that direction will earn you a CVE for sure.
- Adding more features to this mode raises the implementation bar for other TEs, which might lead to low adoption. Esp. if apps what to rely on things, that are differently implemented in TEs (ie. not sure if most/all TEs have the double/triple click metaphor implemented). In the end the feature is unreliable and causes frictions for app devs.

**Comment by textshell** [comment]
> 
>     * Text selection may be the result of different user interactions (depending on what the TE implements here), its not strictly pointer/mouse bound anymore. Means you are leaving mouse realms.

Well, there is not writeup of the protocol yet, but i don't see why terminals can't restrict this to mouse selection if they deem that as appropriate.

The idea here is to keep interaction consistent with non mouse mode by using the terminals original UI.

One very plausible theory why users hate the existing mouse modes is that it make things inconsistent and thus runs counter to muscle memory.

> 
>     * Text selection, while def. useful on alternate buffer where the app can assume to control the screen state, is almost useless on scrollbuffer - due to the mixed output sources from other processes. Here it would be more interesting, if the selected text could be sent along, but anything in that direction will earn you a CVE for sure.

non fullscreen primary screen applications should just ignore selections for parts of the screen they don't care about. Nothing different to the mouse events.

Reading back screen content is something termials really should not do, but some have extensions for that. But as this is intended for allowing to manipulate selected text inside the currently running applications edit area it is totally not needed.

> 
>     * Adding more features to this mode raises the implementation bar for other TEs, which might lead to low adoption. Esp. if apps want to rely on things, that are differently implemented in TEs (ie. not sure if most/all TEs have the double/triple click metaphor implemented). In the end the feature is unreliable and causes frictions for app devs.

I think this is worth experimenting with. I have an application that would be a interesting case to experiment with, but it's not yet at the stage where i can invest time in doing mouse mode experiments.

**Comment by christianparpart** [comment]
Thanks @jerch for looking into this (or the video :D). So thing is. It's **two** VT extensions in this PR currently. The one that initiated the PR and the other one is a mode to enable text selection reporting (or grid cell/range selection reporting, whatever name you prefer).
The idea here is, that it would enable a potential shell to get notified on text selection. The shell then tests if that selection range is actually within the command prompt. if the user then presses DELETE for example. the shell can then accordingly delete that selected range, which -in turn- would invalidate the selection as the underlying content has been destroyed.

Selection events outside of the main page area are NOT reported, because they're actually not addressable anyways.
The app receives selection events for the full main page though.

With this in mind, I don't see (yet) how that could break you or make it hard to implement on either side of the terminal land. hmm 🤔

**Comment by jerch** [comment]
@textshell, @christianparpart

Well turns out this is actually a misunderstanding on my side. I assumed the text selection is part of the passive mouse mode spec, in fact its a separate one in one PR here. So mea cupla for jumping to conclusions.

**Comment by christianparpart** [comment]
I'm going to merge this as EXPERIMENTAL such that app devs can play around with it for at lesat once release cycle. If we find anything inherently wrong, we can change it. However, I kinda doubt it (thinking positively here :) ).

**Pull request merged**
