### PR TITLE
Grid refactor

### PR DESCRIPTION
**Pull request by christianparpart**
## goals

- fix existing grid reflow related bugs and SEGV
- **greatly** improve text throughput performance
- reduce complexity

This PR also fixes: #371

## Checklist

- [x] `ESC c` (RIS, hard reset) not working when LF'ing is moving lines into scrollback.
- [x] #471 VT Parser: use char instead of char32_t, later in Ground state and OSC (/DCS) payloads when UTF-8 is to be expected.
- [ ] #471 Parser: see if we can optimize the FSM to lower the L1/L2 cache pressure.
- [ ] #472 - Screen: refactor Screen<T> API to only know about one Grid<T>, such that we can have a specialized Screen<ThinCell> for primary screen (very thin grid cells) and another specialized Screen<FatCell> for the alternate screen whereas ThinCell is tuned for maximum throughput and FatCell is tuned for fast access of all attributes. - This requires factoring out all that is shared between the two screens, such as at least the modes.
- [ ] #472 Terminal API class acts like a wall, i.e. it does NOT give direct access to `Screen` nor `Grid` nor `Cell` but only via proxy functions and `RenderBuffer` and `RenderCell`, with the goal to have everything behind `Cell` templated.
- [ ] #470 LRU cache: do not use `std::list` but try a runtime fixed size list impl that has zero malloc's during use and it's elements stored in an array. This could even use an std::vector with a wrapper element type to point to prev and next 
- [ ] #473
- [x] Parser: SSE2 for plaintext ASCII throughput (no controls) and a fast-path for ASCII+LF
- [x] Grid: rewrite grid system to be a dense array of Cell objects. (**WIP**)
- [x] Grid: provide API for batched single-line text writes
- [x] Grid: 0-based numbering for line and column adressing.
- [x] Grid Cell: Use LRU cache for hyperlinks instead of `shared_ptr<>` and a unique uint as id key
- [x] Grid Cell: Use LRU cache for image fragments instead of `shared_ptr<>` (is this GPU-effeciently possible?)` , use unique uint as key here too
- [x] Grid Line: trivially copable, contain only start index and count into Grid's Cell array, line flags and initial SGR.
- [x] make Grid and Line a template over T = Cell and possibly an allocator = `std::allocator`

All unchecked parts above have now its own dedicated ticket.

## consequences checklist

- [x] hyperlinks are still working and we'll tested (also LRU implications)
- [x] images are still working (also LRU implications)
- [ ] notcurses demo and info works flawlessly :-D

### CODE REVIEW

**Review by Terrybrar97 — APPROVED** [review]
T

**Review by Terrybrar97 — APPROVED** [review]
T

**Comment by christianparpart** [comment]
```
6   libc++abi.dylib               	    0x7ff800c81472 std::terminate() + 34
7   contour                       	       0x10026b98c crispy::detail::check(bool, std::__1::basic_string_view<char, std::__1::char_traits<char> >, std::__1::basic_string_view<char, std::__1::char_traits<char> >, std::__1::basic_string_view<char, std::__1::char_traits<char> >, int) + 140
8   contour                       	       0x10026ba4e terminal::Grid<terminal::Cell>::lineAt(crispy::boxed<int, terminal::detail::tags::LineOffset>) + 174
9   contour                       	       0x1001e0e4c terminal::Screen<terminal::Terminal>::useCellAt(crispy::boxed<int, terminal::detail::tags::LineOffset>, crispy::boxed<int, terminal::detail::tags::ColumnOffset>) + 44 (Screen.h:466)
10  contour                       	       0x1001e004b terminal::Screen<terminal::Terminal>::at(terminal::Coordinate) + 43 (Screen.h:471)
11  contour                       	       0x100385336 terminal::Terminal::updateCursorHoveringState() + 230
12  contour                       	       0x100385013 terminal::Terminal::sendMouseMoveEvent(terminal::Coordinate, terminal::Modifier, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 259

```

**Comment by data-man** [comment]
Hurray! :rocket:

**Comment by christianparpart** [comment]
Notcurses-demo did find some quirks I yet have to fix. But I had so many
things pending. This is why 0.2.3 is now out to flush the pipeline. So
master branch can head to 0.3.0 - mind, a 0.2.4 can still happen, just not
from master branch. :)

**Pull request merged**
