### PR TITLE
feat: Enable window alert on terminal bells

### PR DESCRIPTION
**Pull request by Ne02ptzero**
With a slight rework of the configuration, as discussed in https://github.com/contour-terminal/contour/issues/1247:

Before:

    bell: "off"

After:

    bell:
      sound: "off"
      alert: true

The original value was moved to bell.sound, and a boolean was added, bell.alert; when this boolean is true, a window alert will be raised each time a bell is ringed.

Closes https://github.com/contour-terminal/contour/issues/1247

### CODE REVIEW

**Review by Yaraslaut — CHANGES_REQUESTED** [review]
I think that by default we can enable this behavior. 
Also, at the moment we do not create documentation for the web page automatically http://contour-terminal.org/
So we need to update it manually, for the configuration this is  `/docs/configuration/profiles.md`

Another issue is update of existing configuration files, so we might want to add this info somewhere so users aware of breaking changes

**Comment by Ne02ptzero** [comment]
> I think that by default we can enable this behavior. 

Sure, thing!

> Another issue is update of existing configuration files, so we might want to add this info somewhere so users aware of breaking changes

How would I do that? Is there any file in the repo to notify the users of breaking changes?

**Comment by Yaraslaut** [comment]
> > I think that by default we can enable this behavior.
> 
> Sure, thing!
> 
> > Another issue is update of existing configuration files, so we might want to add this info somewhere so users aware of breaking changes
> 
> How would I do that? Is there any file in the repo to notify the users of breaking changes?

No, we dont have such,  we can add this info in metainfo file so user can see that configuration entry was moved somewhere

**Comment by Ne02ptzero** [comment]
All right, done. I think since the bell original configuration was never released, the impact should be limited to users using unstable/master builds. Feel free to propose a better change for `metainfo.xml` if my change is not enough.

**Comment by Yaraslaut** [comment]
> All right, done. I think since the bell original configuration was never released, the impact should be limited to users using unstable/master builds. Feel free to propose a better change for `metainfo.xml` if my change is not enough.

Oh, indeed, its been a while since last release and i missed that we added it after previous release, sorry for that, i think better to omit then this comment

**Review by Yaraslaut — APPROVED** [review]
Many thanks @Ne02ptzero

**Comment by christianparpart** [comment]
> Oh, indeed, its been a while since last release and i missed that we added it after previous release, sorry for that, i think better to omit then this comment

Yeah, I really hope we can release 0.4.0 as soon as possible (as in: we feel confident with having master as stable as possible)

**Review by christianparpart — APPROVED** [review]

**Pull request merged**
