### PR TITLE
strong primitive types, v2

### PR DESCRIPTION
**Pull request by christianparpart**
### Ideas

- work out what line number types are absolutely necessary
- make use of PageMargin
- ensure correct use of GridSize::iterator
- booleans replacements: enum class?
- color palette size ?
- Write guidelines on boxed primitives / or blog?
- make use of Rect/Top/Left/Bottom/Right for rectangular VT sequences
- along with that: ensure checksum VT sequence is done!
- reduce warning count in pedantic mode!
-  ..

### CODE REVIEW

**Comment by data-man** [comment]
After this PR Contour crashed:
```
'contour' terminated by signal SIGABRT (Abort)
/Grid.h:756: crispy::range<std::_Deque_iterator<terminal::Line, terminal::Line&, terminal::Line*> > terminal::Grid::lines(terminal::LinePosition, terminal::LinePosition): Assertion `crispy::ascending(LinePosition{0}, _start, LinePosition::cast_from(lines_.size())) && "Absolute scroll offset must not be negative or overflowing."' failed.
```

**Comment by christianparpart** [comment]
What the...! I can check

**Comment by christianparpart** [comment]
Do you have a stack trace for me?

**Comment by christianparpart** [comment]
And is there a way to minimally reproduce this? Apparently that should then also added as test case.

**Comment by data-man** [comment]
Oh, all ok with default config!
And crashes with
```yaml
history:
# Number of lines to preserve (-1 for infinite).
  limit: -1
```

**Comment by data-man** [comment]
> Do you have a stack trace for me?

`$ valgrind contour` will helpful?

```
==20089==    by 0x223C96: terminal::Grid::lines(crispy::boxed<int, terminal::detail::tags::LinePosition>, crispy::boxed<int, terminal::detail::tags::LinePosition>) (Grid.h:756)
==20089==    by 0x270027: terminal::Grid::clampHistory() (Grid.cpp:633)
==20089==    by 0x26E46B: terminal::Grid::setMaxHistoryLineCount(std::optional<crispy::boxed<int, terminal::detail::tags::LineCount> >) (Grid.cpp:305)
==20089==    by 0x212C87: terminal::Screen::setMaxHistoryLineCount(std::optional<crispy::boxed<int, terminal::detail::tags::LineCount> >) (Screen.cpp:417)
==20089==    by 0x1D3523: contour::TerminalSession::configureTerminal() (TerminalSession.cpp:802)
==20089==    by 0x1CEC6D: contour::TerminalSession::TerminalSession(std::unique_ptr<terminal::Pty, std::default_delete<terminal::Pty> >, contour::config::Config, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::unique_ptr<contour::TerminalDisplay, std::default_delete<contour::TerminalDisplay> >, std::function<void ()>) (TerminalSession.cpp:111)
==20089==    by 0x1EBA9B: std::_MakeUniq<contour::TerminalSession>::__single_object std::make_unique<contour::TerminalSession, std::unique_ptr<terminal::PtyProcess, std::default_delete<terminal::PtyProcess> >, contour::config::Config&, bool const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::unique_ptr<contour::TerminalDisplay, std::default_delete<contour::TerminalDisplay> >, contour::TerminalWindow::TerminalWindow(contour::config::Config, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda()#1}>(std::unique_ptr<terminal::PtyProcess, std::default_delete<terminal::PtyProcess> >&&, contour::config::Config&, bool const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::unique_ptr<contour::TerminalDisplay, std::default_delete<contour::TerminalDisplay> >&&, contour::TerminalWindow::TerminalWindow(contour::config::Config, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda()#1}&&) (unique_ptr.h:962)
==20089==    by 0x1EB006: contour::TerminalWindow::TerminalWindow(contour::config::Config, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (TerminalWindow.cpp:221)
```

**Comment by christianparpart** [comment]
> Oh, all ok with default config!
> And crashes with
> 
> ```yaml
> history:
> # Number of lines to preserve (-1 for infinite).
>   limit: -1
> ```

I've a fix for that already, will push later tonight. (sixel images suffer a similar assert, will fix that tonight, too). and I should add tests for those cases then, so CI can catch such things.

**Comment by christianparpart** [comment]
@data-man I did push the fix to master now.

**Comment by data-man** [comment]
Fixed, thank you!

**Pull request merged**
