### PR TITLE
Apply install-deps.sh script changes from 0.2.x branch for enabling GNU/Debian support. Thanks @ssta.

### PR DESCRIPTION
**Pull request by christianparpart**
…

### CODE REVIEW

**Comment by klamonte** [comment]
@christianparpart 

I know only enough about cmake to do

```
mkdir build ; cd build ; cmake .. ; make
```

When I did that today on Debian -- after running install-deps as root and then chown'ing the local packages back to my user because I'm not a sudo'er by default -- I get this:

```
-- [Version] Git branch: master
-- [Version] Git SHA: 21c4dab7
-- [Version] version source: git & /home/autumn/t/contour/Changelog.md
-- [Version] version triple: 0.3.0
-- [Version] version string: 0.3.0-unreleased-master-21c4dab7
-- [ccache] Disabled.
-- [clang-tidy] Disabled.
-- [FilesystemResolver]: Using standard C++ filesystem API
-- addr2line: /usr/bin/addr2line
-- No sanitizer enabled.
-- Embedding 3rdparty libraries ...
-- [ccache] Disabled.
-- [clang-tidy] Disabled.
-- Performing Test fdiagnostics-color=always
-- Performing Test fdiagnostics-color=always - Success
-- Adding compiler flag: -fdiagnostics-color=always.
-- Enabling pedantic compiler options: no
-- [ccache] Disabled.
-- [clang-tidy] Disabled.
-- Adding compiler flag: -fdiagnostics-color=always.
-- Enabling pedantic compiler options: no
-- [code coverage] Disabled.
-- ------------------------------------------------------------------------------
--     libunicode (version 0.0.1)
-- ------------------------------------------------------------------------------
-- Build type:                  RelWithDebInfo
-- Build unit tests:            OFF
-- Build tools:                 OFF
-- Using ccache:                CCACHE-NOTFOUND
-- Using UCD source:            OFF
-- Enable clang-tidy:           OFF ()
-- ------------------------------------------------------------------------------
CMake Error at cmake/ThirdParties.cmake:68 (find_package):
  By not providing "FindMicrosoft.GSL.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Microsoft.GSL", but CMake did not find one.

  Could not find a package configuration file provided by "Microsoft.GSL"
  with any of the following names:

    Microsoft.GSLConfig.cmake
    microsoft.gsl-config.cmake

  Add the installation prefix of "Microsoft.GSL" to CMAKE_PREFIX_PATH or set
  "Microsoft.GSL_DIR" to a directory containing one of the above files.  If
  "Microsoft.GSL" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:81 (include)


-- Configuring incomplete, errors occurred!
See also "/home/autumn/t/contour/build/CMakeFiles/CMakeOutput.log".
See also "/home/autumn/t/contour/build/CMakeFiles/CMakeError.log".
```

Is there something else I should be doing here?

**Comment by klamonte** [comment]
It's actually been a long time since I was able to compile contour from source.  And I'd like to, because it's a nice terminal, and I want to be able to test with it. :)

**Comment by christianparpart** [comment]
> It's actually been a long time since I was able to compile contour from source.  And I'd like to, because it's a nice terminal, and I want to be able to test with it. :)

Hey. Oh that is nice to hear. Please give me some time to look into it, as we a certainly busy with important family duties for at least until tomorrow night.

If not someone else did chime in until then, I certainly will try to improve the setup procedure so that it also works for you.

**Comment by christianparpart** [comment]
What is your precise distro and version you are on?

**Comment by klamonte** [comment]
Family first!  I'm not urgent at all.  :-)

**Comment by klamonte** [comment]
Debian bullseye, currently version 11.1.  g++ 10.2.1, cmake 3.18.4.

**Comment by klamonte** [comment]
I figured I wasn't using cmake correctly.

**Pull request merged**
