### PR TITLE
[Github CI] Adding gentoo ebuild

### PR DESCRIPTION
**Pull request by uspasojevic96**

### CODE REVIEW

**Comment by christianparpart** [comment]
@uspasojevic96 will there be actually any chance to add build testing for Gentoo portage on Github CI? Or is that too much devop'sing for you tonight? :-)

**Comment by uspasojevic96** [comment]
Doubt I am going to finish anything tonight, currently reading up on it and watching couple of videos, but what I had in mind was:
- trigger ebuild install to check gentoo build
- create ebuild file on releases

**Comment by christianparpart** [comment]
yeah no hurries.

**Comment by christianparpart** [comment]
conclusion: maybe later (with more time) :)

**Pull request closed without merging**
