### PR TITLE
Add config option to enable/disable size indicator on resize and make resize indicator small

### PR DESCRIPTION
**Pull request by Utkarsh-khambra**

### CODE REVIEW

**Review by Yaraslaut — DISMISSED** [review]
LGTM
Not sure about default value but can change later
Refs https://github.com/contour-terminal/contour/issues/975

**Comment by Utkarsh-khambra** [comment]
I'd like it to be false by default but just kept it to true for no particular reason. What you guys think.

**Comment by Yaraslaut** [comment]
> I'd like it to be false by default but just kept it to true for no particular reason. What you guys think.

I think that false is also good, personally i dont see this indicator to much, but i guess if  it was bothering you we can set it to false

**Review by christianparpart — APPROVED** [review]
LGTM.

I think true as default is not a bad default. People being annoyed can always disable the setting. And others have the instant feedback. 
Other than that, the default can always be changed in future versions, especially since we want to rework configuration soonish anyways.

**Pull request merged**
