### PR TITLE
Fix a few typos in README.md

### PR DESCRIPTION
**Pull request by Marcool04**
## Description

Hi, just fixed a few typos in the Readme file.
Regards,
Mark.

## Checklist:

- [x] I have read the [**`CONTRIBUTING`**](https://github.com/contour-terminal/contour/blob/master/CONTRIBUTING.md) document in my spoken language, and understand the terms
- [NA] I have updated (or added) the documentation accordingly.
- [NA] I have added tests to cover my changes.
- [x] I have gone through all the steps, and have thoroughly read the instructions

### CODE REVIEW

**Review by uspasojevic96 — APPROVED** [review]

**Comment by uspasojevic96** [comment]
Many thanks, enabled auto-merge

**Review by uspasojevic96 — CHANGES_REQUESTED** [review]
Please squash commits to singular

**Review by christianparpart — APPROVED** [review]

**Comment by christianparpart** [comment]
@Marcool04 Do you need any help in squashing the two commits together into one?

**Comment by Marcool04** [comment]
@christianparpart no sorry, I just didn't have time yet... I'm on it though.

**Comment by Marcool04** [comment]
is that ok now?

**Review by christianparpart — APPROVED** [review]

**Comment by christianparpart** [comment]
> is that ok now?

Absolutely. And yeah, many thanks for reading through our README and fixing the issues you have found. :-)

**Pull request merged**
