### PR TITLE
Update Arch Linux docker

### PR DESCRIPTION
**Pull request by vnepogodin**
Use proper Arch Linux package format
Add AUR repo for building and testing

### CODE REVIEW

**Review by uspasojevic96 — APPROVED** [review]

**Comment by christianparpart** [comment]
FYI: Updated the branch with latest master.

**Comment by christianparpart** [comment]
The Arch Linux Bilder still fails though.

**Comment by uspasojevic96** [comment]
> The Arch Linux Build still fails though.

The error seems to be with `check()` again on AUR in PKGBUILD

**Comment by vnepogodin** [comment]
Test always fails then building with the `makepkg`. In the `src/terminal/Screen_test.cpp` at the line 1737.
image

**Comment by uspasojevic96** [comment]
This is actually interesting, I just ran the tests on my machine and all pass, now do they also pass on Arch Linux when they are manually ran outside of `makepkg` or do they fail?

**Comment by vnepogodin** [comment]
> This is actually interesting, I just ran the tests on my machine and all pass, now do they also pass on Arch Linux when they are manually ran outside of `makepkg` or do they fail?

If building by hand (without `makepkg`) all tests passing

**Comment by christianparpart** [comment]
With tests failing du you mean a compilation or a unit test expectation? Can you maybe send a screenshot of the failure?

Also, you can add the command line flag `-s` to each test executable.

**Comment by vnepogodin** [comment]
> With tests failing du you mean a compilation or a unit test expectation? Can you maybe send a screenshot of the failure?
> 
> Also, you can add the command line flag `-s` to each test executable.

unit test expectation
image

**Pull request merged**
