### PR TITLE
Use CPM

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Review by christianparpart — APPROVED** [review]
LGTM
Thanks. :)

**Comment by data-man** [comment]
> LGTM

PPAU action failed...

**Comment by christianparpart** [comment]
> > LGTM
> 
> PPAU action failed...

"PPAU"?

**Comment by data-man** [comment]
PPA Upload :)

**Comment by christianparpart** [comment]
> PPA Upload :)

Well. Did you try to execute contour from the master branch (of this one?). I seem to have a SEGV right in the b ginning because of YAML (file loading)

**Comment by christianparpart** [comment]
Okay, so doing a `git revert ebb84a9f8b22df33f1e83f80ba394f151aa46e6f` (reverting the PR's commit) actually fixes it. The question now is why is `YAML::LoadFile(...)` SEGV'ting.

**Comment by data-man** [comment]
> Did you try to execute contour from the master branch (of this one?)

Sure (with Qt6).

**Comment by data-man** [comment]
New release! :)
https://github.com/jbeder/yaml-cpp/releases/tag/yaml-cpp-0.7.0

**Comment by christianparpart** [comment]
> New release! :)
> https://github.com/jbeder/yaml-cpp/releases/tag/yaml-cpp-0.7.0

yeah, I tried 0.7.0 too. but still SEGV. All I know is that if I drop the CPM commit locally, it works. But with (so far: no matter what yaml-cpp version) it doesn't. I know it's very odd. It might be some magically added/removed compiler/linker flags? I don't know yet, I had to re-rebase the boxdrawing branch to continue finishing it :-D

On the broken PPA topic, can be fixed seperately. Not too urgent (the SEGV though is) :D

**Comment by data-man** [comment]
> I tried 0.7.0 too. but still SEGV.

What OS?
https://github.com/jbeder/yaml-cpp/issues/985 ?
ccache?

**Comment by christianparpart** [comment]
> > I tried 0.7.0 too. but still SEGV.
> 
> What OS?
> [jbeder/yaml-cpp#985](https://github.com/jbeder/yaml-cpp/issues/985) ?
> ccache?

It's Ubuntu 21.04 latest on my laptop here. ccache was the first I *sadly* cleared as that's suspect number one for me ;)

it's sadly not the mentioned issue in yaml-cpp. I looked around in their issue tracker anddidn't find any. I'll try to digg further (I don't wanna keep dropping that commit, that would be sad).

**Comment by christianparpart** [comment]
@data-man no kidding! The SEGV goes away if I change the order of the `CPMAddPackage()` statements in `ThirdParties.cmake`.

Not sure yet why, but it is reproducible.

**Pull request merged**
