### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by christianparpart** [comment]
image

I'm getting this in another PR, too. But why. hmm...

**Comment by data-man** [comment]
Maybe we are not using the latest versions.
I'll check it later.

**Comment by christianparpart** [comment]
oopsi. merge conflict :)

**Comment by christianparpart** [comment]
The windows-CI thing is something different and still unknown.
But the OS/X breakage I just pushed a fix onto master. You should rebase for that.

p.s.: I work with rebase instead of repeately merging master into working branches. This keeps the history more linear / clean.

**Pull request merged**
